### ISSUE TITLE
Ethernet port on docking station not working

### ISSUE THREAD

**Issue by czebiniak** [danielquinn/Gentoo-Surface-Pro-3#21]
Hello,
Everything is working perfectly on my SP3 except for the ethernet. It shows up whenh I do an ifconfig, but no matter what I do, it never gets a connection.

**Comment by danielquinn** [comment]
Had to edit that issue title ;-)

As I'm not longer using Gentoo on my SP3 I'm afraid all I can do here is offer some general advice:

1. Install lspci and run: `lspci | grep -i eth`.  You should see the name of your newly connected ethernet port... I think.
2. Have a look at your kernel config with `cd /usr/src/linux && make menuconfig` and look for ethernet support resembling what you found in step 1.
3. Enable it, recompile, and re-install, then reboot.

Sorry, I don't really even use my docking station any more so I can't even test this out with my Arch install at the moment.

**Comment by czebiniak** [comment]
Thanks for the info, I had already tried looking at lspci, and for some reason it only responds with 01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
which is not my docking station's ethrnet. I guess it's treating the wifi as ethernet?

**Comment by czebiniak** [comment]
Also,
I do not have any directory under /usr/src at all.

**Comment by czebiniak** [comment]
I'd like to point out that I am indeed using Arch Linux, and not Gentoo. I just figured troubleshooting the ethernet driver  would be pretty similar on both distros. If I am wrong, my apologies.

**Comment by danielquinn** [comment]
As far as I understand, lspci should tell you about all the stuff it sees, regardless of whether or not your kernel supports it, so if it's not showing up in the list, there's a few things that this could mean:

1. It's not a PCI device at all, but a USB one.
2. The ethernet device isn't communicating with the Surface (hardware fault)
3. I have no idea :-(

Assuming that it's \#1 for the moment, then I'd suggest installing `lsusb` (however you get that in Arch/Gentoo) and then run `lsusb | grep -i eth` and see what comes out.  Hopefully, you'll finally get something to work with.

After that, you'll need to get the kernel sources and start looking in there for your newfound ethernet device.  In Gentoo that means installing the kernel sources with `emerge gentoo-sources` which will dump all the stuff into `/usr/src/linux` for you.  At that point you `cd /usr/src/linux && make menuconfig` and then use the (semi-user-friendly) menu that appears to look for your driver.  In Arch, I would imagine this is different, but I'm not sure how.  Do a search for [Arch linux kernel sources](https://duckduckgo.com/?q=arch+linux+kernel+sources&t=ffab&ia=web) and maybe that'll help.

There's also the AUR of course.  I understand that there's a pretty good kernel there called `linux-surface4` and `linux-surface3`.  You might want to experiment to see what works for you: [link](https://aur.archlinux.org/packages/?O=0&K=surface).
