### ISSUE TITLE
No Keyboard

### ISSUE THREAD

**Issue by jrevillard** [danielquinn/Gentoo-Surface-Pro-3#5]
Dear all,

I'm tryin to apply you patch to kernel 4.1.6 (latest gentoo stable) but I cannot get the keybiard working.
Did anybody already tried ?
The think that I don't understand is that,as far as I know, it should work out of the box without any patch isn't it ?

Best,
Jerome

**Comment by danielquinn** [comment]
Indeed, the keyboard should work "out of the box", but I think the touchpad requires the patch.  Depending on the kernel version though -- my experience says that things are still in flux.

For my device, I'm still running 4.1.2, as that's what's supported here, but I've been meaning to try out a later version.  I'm in the midst of a lot of big life things right now though, so progress is slow.  If you manage to get 4.1.6 working, feel free to issue a pull request and I'll try it out on my device.  If it passes, I'll add it to the repo.

Until then though, I'd recommend sticking to 4.1.2 until I, or someone else can submit a working patchset.
